name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn install -f MyWebApp/pom.xml
    - name: Sleep before SonarQube Scan
      run: sleep 60  # Increased sleep duration
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: MyWebApp
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=java-webapp
          -Dsonar.verbose=true
      env:
        SONAR_TOKEN: 'squ_755f36900abcd01a1fd2de3fd37fabb3f4acbee8'
        SONAR_HOST_URL: 'http://172.24.11.76:9000'